export const ADD_CONTACT = "ADD_CONTACT";
export const GET_CONTACTS = "GET_CONTACTS";
export const PUT_CONTACT = "PUT_CONTACT";
export const DELETE_CONTACT = "DLETE_CONTACT";
export const SEARCH_CONTACT = "SEARCH_CONTACT";
